/* Copyright 2026 The ZKX Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Verifies that the ICICLE sumcheck StableHLO (E · (A · B − C) combine,
// Poseidon2 Fiat-Shamir) produces round polynomials matching ICICLE golden
// vectors. Uses deterministic +42 polynomials and seed_rng = 0.

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "gtest/gtest.h"

#include "xla/tsl/platform/env.h"
#include "xla/tsl/platform/path.h"
#include "xla/tsl/platform/status.h"
#include "xla/tsl/platform/statusor.h"
#include "xla/tsl/platform/test_util.h"
#include "zkx/hlo/ir/hlo_module.h"
#include "zkx/literal.h"
#include "zkx/literal_util.h"
#include "zkx/primitive_util.h"
#include "zkx/service/hlo_runner.h"
#include "zkx/service/platform_util.h"
#include "zkx/tools/stablehlo_runner/stablehlo_utils.h"
#include "zkx/tools/stablehlo_runner/sumcheck_testlib.h"

namespace zkx {
namespace {

using sumcheck_testlib::ComputeDeterministicClaimedSum;
using sumcheck_testlib::FillDeterministicPolys;
using sumcheck_testlib::FillDeterministicScalar;
using sumcheck_testlib::FromMontgomery;

std::string GetMlirPath(std::string_view file_name) {
  return tsl::io::JoinPath(tsl::testing::ZkxSrcRoot(), "tools",
                           "stablehlo_runner", file_name);
}

// ICICLE golden vectors for l = 20, deterministic +42 polys,
// Poseidon2-t16 Fiat-Shamir (no labels, seed_rng = 0).
// Generated by: icicle-babybear sumcheck_test_vectors --golden --sizes=20
constexpr uint32_t kExpectedClaimedSum = 542046670;
constexpr int kNumRounds = 20;
constexpr int kNumCoeffs = 4;

// clang-format off
constexpr uint32_t kGoldenRoundPolys[kNumRounds][kNumCoeffs] = {
    {1226356558, 1328956033, 1028899320,  329332147},
    { 782325061,  717818931, 1622427700, 1495468359},
    { 678558762, 1549656861,  136478005,  515885684},
    { 216695594, 1060170942,   83741451, 1515265555},
    {1527046119,    5430261, 1160312441, 1770467185},
    {  95017203, 1873886621, 1751808620,  936742751},
    { 985280224,  730225173,   99354978, 1911241922},
    {1344662517, 1200070070, 1561784966, 1624500811},
    {1329142735, 1700450901,  379909764,  186091511},
    { 897817448,  836046746, 1118201221,  938974095},
    {1810429683, 1117647991, 1573196472, 1969113935},
    {1017875891, 1661463182, 1030286620,  332299204},
    { 995660518, 1590327157, 1447796027, 1373347282},
    { 579869961,  639111327,  123738273,  241605494},
    { 935719247,  665957483,   14005675, 1798016682},
    {1534856281,  362524554,  485279300, 1096136429},
    {1760786439, 1605181852,  963798490,  635231835},
    {  20945081, 1060781866,   75166633,  258481310},
    {1081557325, 1511289485,  237418185, 1984407453},
    { 627709560,  195702154,  502766648,  314099944},
};
// clang-format on

TEST(IcicleSumcheckTest, GoldenVectorsMatchIcicle) {
  // Load FS StableHLO module (l = 20).
  std::string mlir_path = GetMlirPath("icicle_sumcheck_fs_20.stablehlo.mlir");
  std::string module_text;
  TF_ASSERT_OK(
      tsl::ReadFileToString(tsl::Env::Default(), mlir_path, &module_text));

  mlir::MLIRContext context;
  TF_ASSERT_OK_AND_ASSIGN(auto stablehlo_module,
                          ParseStablehloModule(module_text, &context));
  TF_ASSERT_OK_AND_ASSIGN(std::unique_ptr<HloModule> hlo_module,
                          ConvertStablehloToHloModule(*stablehlo_module));

  // Use GPU platform (CPU segfaults on this StableHLO — separate issue).
  TF_ASSERT_OK_AND_ASSIGN(auto platform, PlatformUtil::GetPlatform("gpu"));
  auto runner = std::make_unique<HloRunner>(platform);

  // Create zero-initialized input literals, then fill deterministically.
  const HloComputation* entry = hlo_module->entry_computation();
  std::vector<Literal> inputs;
  inputs.reserve(entry->num_parameters());
  for (int64_t i = 0; i < entry->num_parameters(); ++i) {
    const Shape& shape = entry->parameter_instruction(i)->shape();
    TF_ASSERT_OK_AND_ASSIGN(Literal literal,
                            MakeFakeLiteral(shape, /*use_random=*/false));
    inputs.push_back(std::move(literal));
  }
  ASSERT_GE(inputs.size(), 2u);

  FillDeterministicPolys(inputs[0]);
  int64_t poly_size = inputs[0].shape().dimensions(1);
  uint32_t claimed_sum = ComputeDeterministicClaimedSum(poly_size);
  EXPECT_EQ(claimed_sum, kExpectedClaimedSum);
  FillDeterministicScalar(inputs[1], claimed_sum);

  std::vector<const Literal*> input_ptrs;
  input_ptrs.reserve(inputs.size());
  for (const auto& lit : inputs) {
    input_ptrs.push_back(&lit);
  }

  // Compile and execute.
  TF_ASSERT_OK_AND_ASSIGN(
      auto executable,
      runner->CreateExecutable(std::move(hlo_module), /*run_hlo_passes=*/true));
  TF_ASSERT_OK_AND_ASSIGN(auto device_buffers,
                          runner->TransferLiteralsToDevice(input_ptrs));
  TF_ASSERT_OK_AND_ASSIGN(
      auto exec_result,
      runner->ExecuteWithDeviceBuffers(executable.get(), device_buffers));
  TF_ASSERT_OK_AND_ASSIGN(Literal output, runner->TransferLiteralFromDevice(
                                              std::move(exec_result).Result()));

  // Extract round polynomials from output tuple.
  ASSERT_TRUE(output.shape().IsTuple());
  auto elements = output.DecomposeTuple();
  ASSERT_FALSE(elements.empty());

  const auto& round_polys = elements[0];
  ASSERT_EQ(round_polys.shape().rank(), 2);
  EXPECT_EQ(round_polys.shape().dimensions(0), kNumRounds);
  EXPECT_EQ(round_polys.shape().dimensions(1), kNumCoeffs);

  bool is_mont =
      primitive_util::IsMontgomeryForm(round_polys.shape().element_type());
  const auto* data = static_cast<const uint32_t*>(round_polys.untyped_data());

  for (int r = 0; r < kNumRounds; ++r) {
    for (int c = 0; c < kNumCoeffs; ++c) {
      uint32_t actual = data[r * kNumCoeffs + c];
      if (is_mont) actual = FromMontgomery(actual);
      EXPECT_EQ(actual, kGoldenRoundPolys[r][c])
          << "Mismatch at round_poly[" << r << "][" << c << "]";
    }
  }
}

}  // namespace
}  // namespace zkx
