/* Copyright 2026 The ZKX Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#include "zkx/service/gpu/transforms/poseidon2_fusion_rewriter.h"

#include <memory>
#include <string>

#include "gmock/gmock.h"
#include "gtest/gtest.h"

#include "xla/tsl/platform/env.h"
#include "xla/tsl/platform/path.h"
#include "xla/tsl/platform/statusor.h"
#include "xla/tsl/platform/test_util.h"
#include "zkx/hlo/ir/hlo_computation.h"
#include "zkx/hlo/ir/hlo_instruction.h"
#include "zkx/hlo/ir/hlo_module.h"
#include "zkx/hlo/ir/hlo_opcode.h"
#include "zkx/hlo/parser/hlo_parser.h"
#include "zkx/service/gpu/backend_configs.pb.h"
#include "zkx/tests/hlo_test_base.h"
#include "zkx/zkx_data.pb.h"

namespace zkx::gpu {
namespace {

class Poseidon2FusionRewriterTest : public HloTestBase {
 protected:
  // Loads an HloModule from an HLO text file in the testdata directory.
  absl::StatusOr<std::unique_ptr<HloModule>> LoadModuleFromText(
      std::string_view filename) {
    std::string path =
        tsl::io::JoinPath(tsl::testing::ZkxSrcRoot(), "service", "gpu",
                          "transforms", "testdata", filename);
    std::string hlo_text;
    TF_RETURN_IF_ERROR(
        tsl::ReadFileToString(tsl::Env::Default(), path, &hlo_text));
    return ParseAndReturnUnverifiedModule(hlo_text);
  }
};

// Verifies that a module with no while loops is not changed.
TEST_F(Poseidon2FusionRewriterTest, NoWhileLoops) {
  auto module = ParseAndReturnVerifiedModule(R"(
    HloModule no_whiles

    ENTRY main {
      %p0 = s32[16] parameter(0)
      ROOT %add = s32[16] add(%p0, %p0)
    }
  )")
                    .value();

  Poseidon2FusionRewriter rewriter;
  TF_ASSERT_OK_AND_ASSIGN(bool changed, rewriter.Run(module.get(), {}));
  EXPECT_FALSE(changed);
}

// Verifies pattern matching on the actual BabyBear16 Poseidon2 HLO
// (width=16, ext_rounds=4, int_rounds=13, sbox_degree=7).
// The HLO text is generated by tracing Python's Poseidon2BabyBear16.permute()
// through JAX with jax.lax.while_loop, producing 3 kWhile instructions.
TEST_F(Poseidon2FusionRewriterTest, BabyBear16Permute) {
  TF_ASSERT_OK_AND_ASSIGN(auto module,
                          LoadModuleFromText("poseidon2_babybear16.hlo"));

  Poseidon2FusionRewriter rewriter;
  TF_ASSERT_OK_AND_ASSIGN(bool changed, rewriter.Run(module.get(), {}));
  EXPECT_TRUE(changed);

  // Find the poseidon2 fusion instruction. The rewriter iterates all
  // non-fusion computations, so the fusion may be created in a sub-computation
  // (e.g. permute.223) rather than the entry computation.
  const HloInstruction* fusion = nullptr;
  for (HloComputation* comp : module->computations()) {
    for (const HloInstruction* instr : comp->instructions()) {
      if (instr->opcode() == HloOpcode::kFusion) {
        fusion = instr;
        break;
      }
    }
    if (fusion) break;
  }

  ASSERT_NE(fusion, nullptr) << "Expected a fusion instruction";
  EXPECT_EQ(fusion->fusion_kind(), HloInstruction::FusionKind::kCustom);

  // Check backend config.
  auto gpu_config = fusion->backend_config<GpuBackendConfig>();
  ASSERT_TRUE(gpu_config.ok());
  const auto& backend_config = gpu_config->fusion_backend_config();
  EXPECT_EQ(backend_config.kind(), "__custom_fusion");
  EXPECT_EQ(backend_config.custom_fusion_config().name(),
            "poseidon2:16:4:13:7");

  // Verify fusion has 5 operands: state, ext_init_rc, int_rc, ext_term_rc,
  // diag.
  EXPECT_EQ(fusion->operand_count(), 5);

  // Verify operand shapes.
  EXPECT_EQ(fusion->operand(0)->shape().element_type(), BABYBEAR_MONT);
  EXPECT_EQ(fusion->operand(0)->shape().dimensions(0), 16);
  // ext_init_rc: babybear_mont[4,16]
  EXPECT_EQ(fusion->operand(1)->shape().rank(), 2);
  EXPECT_EQ(fusion->operand(1)->shape().dimensions(0), 4);
  EXPECT_EQ(fusion->operand(1)->shape().dimensions(1), 16);
  // int_rc: babybear_mont[13]
  EXPECT_EQ(fusion->operand(2)->shape().rank(), 1);
  EXPECT_EQ(fusion->operand(2)->shape().dimensions(0), 13);
  // ext_term_rc: babybear_mont[4,16]
  EXPECT_EQ(fusion->operand(3)->shape().rank(), 2);
  // diag: babybear_mont[16]
  EXPECT_EQ(fusion->operand(4)->shape().rank(), 1);
  EXPECT_EQ(fusion->operand(4)->shape().dimensions(0), 16);
}

}  // namespace
}  // namespace zkx::gpu
