// Copyright 2025 The PrimeIR Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ==============================================================================

// RUN: prime-ir-opt -canonicalize %s | FileCheck %s -enable-var-scope

!PF17 = !field.pf<17:i32>
!PF17m = !field.pf<17:i32, true>

//===----------------------------------------------------------------------===//
// Constant Folding
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_negate_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_negate_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 12 : [[T]]
  // -5 mod 17 = 12
  %0 = field.constant 5 : !PF17
  %1 = field.negate %0 : !PF17
  // CHECK-NOT: field.negate
  // CHECK: return %[[C]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_negate_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_negate_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[14, 12]> : [[T]]
  // -[3, 5] mod 17 = [14, 12]
  %0 = field.constant dense<[3, 5]> : tensor<2x!PF17>
  %1 = field.negate %0 : tensor<2x!PF17>
  // CHECK-NOT: field.negate
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_double_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_double_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 14 : [[T]]
  // 2 * 7 mod 17 = 14
  %0 = field.constant 7 : !PF17
  %1 = field.double %0 : !PF17
  // CHECK-NOT: field.double
  // CHECK: return %[[C]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_double_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_double_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[6, 16]> : [[T]]
  // 2 * [3, 8] mod 17 = [6, 16]
  %0 = field.constant dense<[3, 8]> : tensor<2x!PF17>
  %1 = field.double %0 : tensor<2x!PF17>
  // CHECK-NOT: field.double
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_square_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_square_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 9 : [[T]]
  // 3² mod 17 = 9
  %0 = field.constant 3 : !PF17
  %1 = field.square %0 : !PF17
  // CHECK-NOT: field.square
  // CHECK: return %[[C]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_square_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_square_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[4, 15]> : [[T]]
  // [2, 7]² mod 17 = [4, 49 mod 17] = [4, 15]
  %0 = field.constant dense<[2, 7]> : tensor<2x!PF17>
  %1 = field.square %0 : tensor<2x!PF17>
  // CHECK-NOT: field.square
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_inverse_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_inverse_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 6 : [[T]]
  // 3⁻¹ mod 17: 3 * 6 = 18 = 1 mod 17, so 3⁻¹ = 6
  %0 = field.constant 3 : !PF17
  %1 = field.inverse %0 : !PF17
  // CHECK-NOT: field.inverse
  // CHECK: return %[[C]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_inverse_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_inverse_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[9, 6]> : [[T]]
  // 2⁻¹ mod 17: 2 * 9 = 18 = 1 mod 17, so 2⁻¹ = 9
  // 3⁻¹ mod 17: 3 * 6 = 18 = 1 mod 17, so 3⁻¹ = 6
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = field.inverse %0 : tensor<2x!PF17>
  // CHECK-NOT: field.inverse
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_inverse_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_inverse_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<9> : [[T]]
  // 2⁻¹ mod 17: 2 * 9 = 18 = 1 mod 17, so 2⁻¹ = 9
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.inverse %0 : tensor<2x!PF17>
  // CHECK-NOT: field.inverse
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_add_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_add_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 5 : [[T]]
  // 2 + 3 mod 17 = 5
  %0 = field.constant 2 : !PF17
  %1 = field.constant 3 : !PF17
  %2 = field.add %0, %1 : !PF17
  // CHECK-NOT: field.add
  // CHECK: return %[[C]] : [[T]]
  return %2 : !PF17
}

// CHECK-LABEL: @test_add_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_add_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[6, 5]> : [[T]]
  // [2, 3] + [4, 2] mod 17 = [6, 5]
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = field.constant dense<[4, 2]> : tensor<2x!PF17>
  %2 = field.add %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.add
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_add_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_add_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<6> : [[T]]
  // [2] + [4] mod 17 = [6]
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.constant dense<4> : tensor<2x!PF17>
  %2 = field.add %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.add
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_sub_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_sub_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 16 : [[T]]
  // 2 - 3 mod 17 = 16
  %0 = field.constant 2 : !PF17
  %1 = field.constant 3 : !PF17
  %2 = field.sub %0, %1 : !PF17
  // CHECK-NOT: field.sub
  // CHECK: return %[[C]] : [[T]]
  return %2 : !PF17
}

// CHECK-LABEL: @test_sub_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_sub_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[15, 1]> : [[T]]
  // [2, 3] - [4, 2] mod 17 = [15, 1]
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = field.constant dense<[4, 2]> : tensor<2x!PF17>
  %2 = field.sub %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.sub
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_sub_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_sub_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<15> : [[T]]
  // [2] - [4] mod 17 = [15]
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.constant dense<4> : tensor<2x!PF17>
  %2 = field.sub %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.sub
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_double_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_double_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<4> : [[T]]
  // 2 * 2 mod 17 = 4
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.double %0 : tensor<2x!PF17>
  // CHECK-NOT: field.double
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_square_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_square_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<4> : [[T]]
  // 2² mod 17 = 4
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.square %0 : tensor<2x!PF17>
  // CHECK-NOT: field.square
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_mul_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_mul_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 6 : [[T]]
  // 2 * 3 mod 17 = 6
  %0 = field.constant 2 : !PF17
  %1 = field.constant 3 : !PF17
  %2 = field.mul %0, %1 : !PF17
  // CHECK-NOT: field.mul
  // CHECK: return %[[C]] : [[T]]
  return %2 : !PF17
}

// CHECK-LABEL: @test_mul_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_mul_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[8, 6]> : [[T]]
  // [2, 3] * [4, 2] mod 17 = [8, 6]
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = field.constant dense<[4, 2]> : tensor<2x!PF17>
  %2 = field.mul %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.mul
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_mul_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_mul_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<8> : [[T]]
  // [2] * [4] mod 17 = [8]
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.constant dense<4> : tensor<2x!PF17>
  %2 = field.mul %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.mul
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_negate_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_negate_splat_tensor_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<15> : [[T]]
  // -2 mod 17 = 15
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.negate %0 : tensor<2x!PF17>
  // CHECK-NOT: field.negate
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_negate_tensor_zero_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_negate_tensor_zero_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<0> : [[T]]
  // -0 mod 17 = 0
  %0 = field.constant dense<0> : tensor<2x!PF17>
  %1 = field.negate %0 : tensor<2x!PF17>
  // CHECK-NOT: field.negate
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

//===----------------------------------------------------------------------===//
// AddOp patterns
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_add_zero_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_zero_is_self(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 0 : !PF17
  %1 = field.add %arg0, %0 : !PF17
  // CHECK: return %[[ARG0]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_add_tensor_zero_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_tensor_zero_is_self(%arg0: tensor<2x!PF17>) -> tensor<2x!PF17> {
  %0 = field.constant dense<0> : tensor<2x!PF17>
  %1 = field.add %arg0, %0 : tensor<2x!PF17>
  // CHECK: return %[[ARG0]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_add_constant_twice
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_constant_twice(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.add %arg0, %c1 : !PF17
  %1 = field.add %0, %c2 : !PF17
  // CHECK: %[[C3:.*]] = field.constant 3 : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[C3]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_add_constant_to_sub_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_constant_to_sub_lhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %c1, %arg0 : !PF17
  %1 = field.add %0, %c2 : !PF17
  // CHECK: %[[C3:.*]] = field.constant 3 : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[C3]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_add_constant_to_sub_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_constant_to_sub_rhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %arg0, %c1 : !PF17
  %1 = field.add %0, %c2 : !PF17
  // CHECK: %[[C1:.*]] = field.constant 1 : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[C1]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_add_self_is_double
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_add_self_is_double(%arg0: !PF17) -> !PF17 {
  %add = field.add %arg0, %arg0 : !PF17
  // CHECK: %[[RES:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %add : !PF17
}

// CHECK-LABEL: @test_add_both_negated
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_add_both_negated(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg0 = field.negate %arg0 : !PF17
  %neg1 = field.negate %arg1 : !PF17
  %add = field.add %neg0, %neg1 : !PF17
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[ADD]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %add : !PF17
}

// CHECK-LABEL: @test_add_after_sub
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_add_after_sub(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %sub = field.sub %arg0, %arg1 : !PF17
  %add = field.add %sub, %arg1 : !PF17
  // CHECK: return %[[ARG0]] : [[T]]
  return %add : !PF17
}

// CHECK-LABEL: @test_add_after_neg_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_add_after_neg_lhs(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg = field.negate %arg0 : !PF17
  %add = field.add %neg, %arg1 : !PF17
  // CHECK: %[[RES:.*]] = field.sub %[[ARG1]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %add : !PF17
}

// CHECK-LABEL: @test_add_after_neg_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_add_after_neg_rhs(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg = field.negate %arg1 : !PF17
  %add = field.add %arg0, %neg : !PF17
  // CHECK: %[[RES:.*]] = field.sub %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %add : !PF17
}

// CHECK-LABEL: @test_factor_mul_add
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]], %[[ARG2:.*]]: [[T]]) -> [[T]]
func.func @test_factor_mul_add(%arg0: !PF17, %arg1: !PF17, %arg2: !PF17) -> !PF17 {
  %mul1 = field.mul %arg0, %arg1 : !PF17
  %mul2 = field.mul %arg0, %arg2 : !PF17
  %add = field.add %mul1, %mul2 : !PF17
  // CHECK: %[[ADD:.*]] = field.add %[[ARG1]], %[[ARG2]] : [[T]]
  // CHECK: %[[RES:.*]] = field.mul %[[ARG0]], %[[ADD]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %add : !PF17
}

//===----------------------------------------------------------------------===//
// SubOp patterns
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_sub_zero_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_zero_is_self(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 0 : !PF17
  %1 = field.sub %arg0, %0 : !PF17
  // CHECK: return %[[ARG0]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_tensor_zero_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_tensor_zero_is_self(%arg0: tensor<2x!PF17>) -> tensor<2x!PF17> {
  %0 = field.constant dense<0> : tensor<2x!PF17>
  %1 = field.sub %arg0, %0 : tensor<2x!PF17>
  // CHECK: return %[[ARG0]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_sub_constant_from_add
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_constant_from_add(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.add %arg0, %c1 : !PF17
  %1 = field.sub %0, %c2 : !PF17
  // CHECK: %[[C16:.*]] = field.constant 16 : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[C16]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_constant_twice_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_constant_twice_lhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %c1, %arg0 : !PF17
  %1 = field.sub %0, %c2 : !PF17
  // CHECK: %[[C16:.*]] = field.constant 16 : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[C16]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_constant_twice_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_constant_twice_rhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %arg0, %c1 : !PF17
  %1 = field.sub %0, %c2 : !PF17
  // CHECK: %[[C3:.*]] = field.constant 3 : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[ARG0]], %[[C3]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_add_from_constant
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_add_from_constant(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.add %arg0, %c1 : !PF17
  %1 = field.sub %c2, %0 : !PF17
  // CHECK: %[[C1:.*]] = field.constant 1 : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[C1]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_sub_from_constant_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_sub_from_constant_lhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %c1, %arg0 : !PF17
  %1 = field.sub %c2, %0 : !PF17
  // CHECK: %[[C1:.*]] = field.constant 1 : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[C1]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_sub_from_constant_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_sub_from_constant_rhs(%arg0: !PF17) -> !PF17 {
  %c1 = field.constant 1 : !PF17
  %c2 = field.constant 2 : !PF17
  %0 = field.sub %arg0, %c1 : !PF17
  %1 = field.sub %c2, %0 : !PF17
  // CHECK: %[[C3:.*]] = field.constant 3 : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[C3]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_sub_self_is_zero
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_sub_self_is_zero(%arg0: !PF17) -> !PF17 {
  %0 = field.sub %arg0, %arg0 : !PF17
  // CHECK: %[[C:.*]] = field.constant 0 : [[T]]
  // CHECK: return %[[C]] : [[T]]
  return %0 : !PF17
}

// CHECK-LABEL: @test_sub_lhs_after_add
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_lhs_after_add(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %add = field.add %arg0, %arg1 : !PF17
  %sub = field.sub %add, %arg0 : !PF17
  // CHECK: return %[[ARG1]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_sub_rhs_after_add
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_rhs_after_add(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %add = field.add %arg0, %arg1 : !PF17
  %sub = field.sub %add, %arg1 : !PF17
  // CHECK: return %[[ARG0]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_sub_lhs_after_sub
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_lhs_after_sub(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %sub1 = field.sub %arg0, %arg1 : !PF17
  %sub2 = field.sub %sub1, %arg0 : !PF17
  // CHECK: %[[RES:.*]] = field.negate %[[ARG1]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub2 : !PF17
}

// CHECK-LABEL: @test_sub_after_neg_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_after_neg_lhs(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg = field.negate %arg0 : !PF17
  %sub = field.sub %neg, %arg1 : !PF17
  // CHECK: %[[SUM:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[SUM]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_sub_after_neg_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_after_neg_rhs(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg = field.negate %arg1 : !PF17
  %sub = field.sub %arg0, %neg : !PF17
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_sub_both_negated
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_both_negated(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %neg0 = field.negate %arg0 : !PF17
  %neg1 = field.negate %arg1 : !PF17
  %sub = field.sub %neg0, %neg1 : !PF17
  // CHECK: %[[RES:.*]] = field.sub %[[ARG1]], %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_sub_after_square_both
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_sub_after_square_both(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %sq0 = field.square %arg0 : !PF17
  %sq1 = field.square %arg1 : !PF17
  %sub = field.sub %sq0, %sq1 : !PF17
  // CHECK: %[[SUB:.*]] = field.sub %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.mul %[[SUB]], %[[ADD]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub : !PF17
}

// CHECK-LABEL: @test_factor_mul_sub
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]], %[[ARG2:.*]]: [[T]]) -> [[T]]
func.func @test_factor_mul_sub(%arg0: !PF17, %arg1: !PF17, %arg2: !PF17) -> !PF17 {
  %mul1 = field.mul %arg0, %arg1 : !PF17
  %mul2 = field.mul %arg0, %arg2 : !PF17
  %sub = field.sub %mul1, %mul2 : !PF17
  // CHECK: %[[SUB:.*]] = field.sub %[[ARG1]], %[[ARG2]] : [[T]]
  // CHECK: %[[RES:.*]] = field.mul %[[ARG0]], %[[SUB]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %sub : !PF17
}

//===----------------------------------------------------------------------===//
// MulOp patterns
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_mul_by_zero_is_zero
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_zero_is_zero(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 0 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[C:.*]] = field.constant 0 : [[T]]
  // CHECK: return %[[C]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_tensor_by_zero_is_zero
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_tensor_by_zero_is_zero(%arg0: tensor<2x!PF17>) -> tensor<2x!PF17> {
  %0 = field.constant dense<0> : tensor<2x!PF17>
  %1 = field.mul %arg0, %0 : tensor<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<0> : [[T]]
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_mul_by_one_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_one_is_self(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 1 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: return %[[ARG0]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_tensor_by_one_is_self
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_tensor_by_one_is_self(%arg0: tensor<2x!PF17>) -> tensor<2x!PF17> {
  %0 = field.constant dense<1> : tensor<2x!PF17>
  %1 = field.mul %arg0, %0 : tensor<2x!PF17>
  // CHECK: return %[[ARG0]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_mul_by_two_is_double
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_two_is_double(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 2 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[RES:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_self_is_square
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_self_is_square(%arg0: !PF17) -> !PF17 {
  %mul = field.mul %arg0, %arg0 : !PF17
  // CHECK: %[[RES:.*]] = field.square %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %mul : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_one
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_one(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 16 : !PF17 // -1 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[RES:.*]] = field.negate %[[ARG0]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_two
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_two(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 15 : !PF17 // -2 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[DOUBLE]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_three
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_three(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 14 : !PF17 // -3 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[DOUBLE]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[ADD]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_four
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_four(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 13 : !PF17 // -4 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[DOUBLE2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_three
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_three(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 3 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[DOUBLE]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_four
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_four(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 4 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[RES:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_five
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_five(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 5 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[DOUBLE2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_six
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_six(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 6 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[DOUBLE1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.double %[[ADD]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_seven
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_seven(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 7 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[ADD1:.*]] = field.add %[[ARG0]], %[[DOUBLE1]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[ADD1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[DOUBLE2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_eight
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_eight(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 8 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.double %[[DOUBLE2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_nine
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_nine(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 9 : !PF17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: %[[DOUBLE3:.*]] = field.double %[[DOUBLE2]] : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[ARG0]], %[[DOUBLE3]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_five
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_five(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 12 : !PF17 // -5 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[DOUBLE1]] : [[T]]
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[DOUBLE2]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[ADD]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_six
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_six(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 11 : !PF17 // -6 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[DOUBLE1]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[ADD]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[DOUBLE2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_by_neg_seven
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_by_neg_seven(%arg0: !PF17) -> !PF17 {
  %0 = field.constant 10 : !PF17 // -7 mod 17
  %1 = field.mul %arg0, %0 : !PF17
  // CHECK: %[[DOUBLE1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[ADD1:.*]] = field.add %[[ARG0]], %[[DOUBLE1]] : [[T]]
  // CHECK: %[[DOUBLE2:.*]] = field.double %[[ADD1]] : [[T]]
  // CHECK: %[[ADD2:.*]] = field.add %[[ARG0]], %[[DOUBLE2]] : [[T]]
  // CHECK: %[[RES:.*]] = field.negate %[[ADD2]] : [[T]]
  // CHECK: return %[[RES]]
  return %1 : !PF17
}

// Note: test_mul_by_neg_eight and test_mul_by_neg_nine are not tested here
// because in PF17, constants 9 and 8 collide with positive patterns (IsNine,
// IsEight). These are tested in ModArith tests with p=37 where no collision
// occurs.

// CHECK-LABEL: @test_mul_constant_twice
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_constant_twice(%arg0: !PF17) -> !PF17 {
  %c3 = field.constant 3 : !PF17
  %c4 = field.constant 4 : !PF17
  %0 = field.mul %arg0, %c3 : !PF17
  %1 = field.mul %0, %c4 : !PF17
  // x * 3 -> x + double(x), then * 4 -> double(double(...))
  // CHECK: %[[D1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[A1:.*]] = field.add %[[ARG0]], %[[D1]] : [[T]]
  // CHECK: %[[D2:.*]] = field.double %[[A1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.double %[[D2]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_of_mul_by_constant
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]], %[[ARG1:.*]]: [[T]]) -> [[T]]
func.func @test_mul_of_mul_by_constant(%arg0: !PF17, %arg1: !PF17) -> !PF17 {
  %c3 = field.constant 3 : !PF17
  %c4 = field.constant 4 : !PF17
  %0 = field.mul %arg0, %c3 : !PF17
  %1 = field.mul %arg1, %c4 : !PF17
  %2 = field.mul %0, %1 : !PF17
  // x * 3 -> x + double(x), y * 4 -> double(double(y))
  // CHECK: %[[D0:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[A0:.*]] = field.add %[[ARG0]], %[[D0]] : [[T]]
  // CHECK: %[[D1:.*]] = field.double %[[ARG1]] : [[T]]
  // CHECK: %[[D2:.*]] = field.double %[[D1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.mul %[[A0]], %[[D2]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %2 : !PF17
}

// CHECK-LABEL: @test_mul_add_distribute_constant
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_add_distribute_constant(%arg0: !PF17) -> !PF17 {
  %c3 = field.constant 3 : !PF17
  %c4 = field.constant 4 : !PF17
  %0 = field.add %arg0, %c3 : !PF17
  %1 = field.mul %0, %c4 : !PF17
  // (x + 3) * 4 -> x * 4 + 12, then x * 4 -> double(double(x))
  // CHECK: %[[C12:.*]] = field.constant 12 : [[T]]
  // CHECK: %[[D1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[D2:.*]] = field.double %[[D1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.add %[[D2]], %[[C12]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_sub_distribute_constant_rhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_sub_distribute_constant_rhs(%arg0: !PF17) -> !PF17 {
  %c3 = field.constant 3 : !PF17
  %c4 = field.constant 4 : !PF17
  %0 = field.sub %arg0, %c3 : !PF17
  %1 = field.mul %0, %c4 : !PF17
  // (x - 3) * 4 -> x * 4 - 12, then x * 4 -> double(double(x))
  // CHECK: %[[C12:.*]] = field.constant 12 : [[T]]
  // CHECK: %[[D1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[D2:.*]] = field.double %[[D1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[D2]], %[[C12]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

// CHECK-LABEL: @test_mul_sub_distribute_constant_lhs
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_mul_sub_distribute_constant_lhs(%arg0: !PF17) -> !PF17 {
  %c3 = field.constant 3 : !PF17
  %c4 = field.constant 4 : !PF17
  %0 = field.sub %c3, %arg0 : !PF17
  %1 = field.mul %0, %c4 : !PF17
  // (3 - x) * 4 -> 12 - x * 4, then x * 4 -> double(double(x))
  // CHECK: %[[C12:.*]] = field.constant 12 : [[T]]
  // CHECK: %[[D1:.*]] = field.double %[[ARG0]] : [[T]]
  // CHECK: %[[D2:.*]] = field.double %[[D1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.sub %[[C12]], %[[D2]] : [[T]]
  // CHECK: return %[[RES]] : [[T]]
  return %1 : !PF17
}

//===----------------------------------------------------------------------===//
// Tensor operations
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tensor_from_elements
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_tensor_from_elements() -> tensor<2x!PF17> {
  %0 = field.constant 1 : !PF17
  %1 = field.constant 2 : !PF17
  %2 = tensor.from_elements %0, %1 : tensor<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<[1, 2]> : [[T]]
  // CHECK-NOT: tensor.from_elements
  // CHECK: return %[[C:.*]] : [[T]]
  return %2 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_tensor_extract
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_tensor_extract() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 3 : [[T]]
  // CHECK-NOT: tensor.extract
  // CHECK: return %[[C]] : [[T]]
  %c1 = arith.constant 1: index
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = tensor.extract %0[%c1] : tensor<2x!PF17>
  return %1 : !PF17
}

// CHECK-LABEL: @test_tensor_splat_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_tensor_splat_fold() -> tensor<4x!PF17> {
  %0 = field.constant 9 : !PF17
  %1 = tensor.splat %0 : tensor<4x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<9> : [[T]]
  // CHECK-NOT: tensor.splat
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<4x!PF17>
}

// CHECK-LABEL: @test_reshape_splat_constant_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_reshape_splat_constant_fold() -> tensor<2x2x!PF17> {
  %0 = field.constant dense<5> : tensor<4x!PF17>
  %shape = arith.constant dense<[2, 2]> : tensor<2xi32>
  %1 = tensor.reshape %0(%shape) : (tensor<4x!PF17>, tensor<2xi32>) -> tensor<2x2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<5> : [[T]]
  // CHECK-NOT: tensor.reshape
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x2x!PF17>
}

// CHECK-LABEL: @test_extract_slice_splat_constant_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_extract_slice_splat_constant_fold() -> tensor<2x!PF17> {
  %0 = field.constant dense<7> : tensor<4x!PF17>
  %1 = tensor.extract_slice %0[1] [2] [1] : tensor<4x!PF17> to tensor<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<7> : [[T]]
  // CHECK-NOT: tensor.extract_slice
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_gather_splat_constant_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_gather_splat_constant_fold() -> tensor<2x1x!PF17> {
  %0 = field.constant dense<3> : tensor<4x!PF17>
  %indices = arith.constant dense<[[0], [2]]> : tensor<2x1xindex>
  %1 = tensor.gather %0[%indices] gather_dims([0]) : (tensor<4x!PF17>, tensor<2x1xindex>) -> tensor<2x1x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<3> : [[T]]
  // CHECK-NOT: tensor.gather
  // CHECK: return %[[C]] : [[T]]
  return %1 : tensor<2x1x!PF17>
}

//===----------------------------------------------------------------------===//
// Vector operations
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_vector_from_elements
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_vector_from_elements() -> vector<2x!PF17> {
  %0 = field.constant 1 : !PF17
  %1 = field.constant 2 : !PF17
  %2 = vector.from_elements %0, %1 : vector<2x!PF17>
  // CHECK: %[[FROM_ELEMENTS:.*]] = field.constant dense<[1, 2]> : [[T]]
  // CHECK-NOT: vector.from_elements
  // CHECK: return %[[FROM_ELEMENTS:.*]] : [[T]]
  return %2 : vector<2x!PF17>
}

// CHECK-LABEL: @test_vector_extract
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_vector_extract() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 3 : [[T]]
  // CHECK-NOT: vector.extract
  // CHECK: return %[[C]] : [[T]]
  %0 = field.constant dense<[2, 3]> : vector<2x!PF17>
  %1 = vector.extract %0[1] : !PF17 from vector<2x!PF17>
  return %1 : !PF17
}

// CHECK-LABEL: @test_splat_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_splat_fold() -> vector<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<1> : [[T]]
  // CHECK-NOT: vector.splat
  // CHECK: return %[[C]] : [[T]]
  %0 = field.constant 1 : !PF17
  %1 = vector.splat %0 : vector<2x!PF17>
  return %1 : vector<2x!PF17>
}

// CHECK-LABEL: @test_shuffle_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_shuffle_fold() -> vector<4x!PF17> {
  %v1 = field.constant dense<[10, 3, 13, 16]> : vector<4x!PF17>
  %v2 = field.constant dense<[15, 8]> : vector<2x!PF17>
  %shuffled = vector.shuffle %v1, %v2 [0, 4, 1, 5] : vector<4x!PF17>, vector<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<[10, 15, 3, 8]> : [[T]]
  // CHECK-NOT: vector.shuffle
  // CHECK: return %[[C]] : [[T]]
  return %shuffled : vector<4x!PF17>
}

// CHECK-LABEL: @test_extract_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_extract_fold() -> vector<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[3, 4]> : [[T]]
  // CHECK-NOT: vector.extract
  // CHECK: return %[[C]] : [[T]]
  %0 = field.constant dense<[[1, 2],[3, 4]]> : vector<2x2x!PF17>
  %1 = vector.extract %0[1] : vector<2x!PF17> from vector<2x2x!PF17>
  return %1 : vector<2x!PF17>
}

// CHECK-LABEL: @test_extract_fold_from_splat
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_extract_fold_from_splat() -> vector<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<1> : [[T]]
  // CHECK-NOT: vector.extract
  // CHECK: return %[[C]] : [[T]]
  %0 = field.constant dense<1> : vector<2x2x!PF17>
  %1 = vector.extract %0[1] : vector<2x!PF17> from vector<2x2x!PF17>
  return %1 : vector<2x!PF17>
}

// CHECK-LABEL: @test_broadcast_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_broadcast_fold() -> vector<2x2x!PF17> {
  %0 = field.constant 5 : !PF17
  %1 = vector.broadcast %0 : !PF17 to vector<2x2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<5> : [[T]]
  // CHECK-NOT: vector.broadcast
  // CHECK: return %[[C]] : [[T]]
  return %1 : vector<2x2x!PF17>
}

// CHECK-LABEL: @test_broadcast_splat_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_broadcast_splat_fold() -> vector<2x2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<5> : [[T]]
  // CHECK-NOT: vector.broadcast
  // CHECK: return %[[C]] : [[T]]
  %1 = field.constant dense<5> : vector<2x!PF17>
  %2 = vector.broadcast %1 : vector<2x!PF17> to vector<2x2x!PF17>
  return %2 : vector<2x2x!PF17>
}

// CHECK-LABEL: @test_insert_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_insert_fold() -> vector<2x!PF17> {
  %0 = field.constant dense<[1, 3]> : vector<2x!PF17>
  %1 = field.constant 2 : !PF17
  %result = vector.insert %1, %0[1] : !PF17 into vector<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<[1, 2]> : [[T]]
  // CHECK-NOT: vector.insert
  // CHECK: return %[[C]] : [[T]]
  return %result : vector<2x!PF17>
}

// CHECK-LABEL: @test_insert_strided_slice_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_insert_strided_slice_fold() -> vector<4x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[3, 1, 2, 3]> : [[T]]
  // CHECK-NOT: vector.insert_strided_slice
  // CHECK: return %[[C]] : [[T]]
  %source = field.constant dense<[1, 2]> : vector<2x!PF17>
  %dest = field.constant dense<3> : vector<4x!PF17>
  %result = vector.insert_strided_slice %source, %dest
            {offsets = [1], strides = [1]}
            : vector<2x!PF17> into vector<4x!PF17>
  return %result : vector<4x!PF17>
}


// CHECK-LABEL: @test_extract_strided_slice_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_extract_strided_slice_fold() -> vector<2x!PF17> {
  %0 = field.constant dense<[1, 2, 3, 4]> : vector<4x!PF17>
  %slice = vector.extract_strided_slice %0 {offsets = [0], sizes = [2], strides = [1]} : vector<4x!PF17> to vector<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<[1, 2]> : [[T]]
  // CHECK-NOT: vector.extract_strided_slice
  // CHECK: return %[[C]] : [[T]]
  return %slice : vector<2x!PF17>
}

// CHECK-LABEL: @test_splat_extract_strided_slice_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_splat_extract_strided_slice_fold() -> vector<2x!PF17> {
  %0 = field.constant dense<5> : vector<4x!PF17>
  %slice = vector.extract_strided_slice %0 {offsets = [0], sizes = [2], strides = [1]} : vector<4x!PF17> to vector<2x!PF17>
  // CHECK: %[[C:.*]] = field.constant dense<5> : [[T]]
  // CHECK-NOT: vector.extract_strided_slice
  // CHECK: return %[[C]] : [[T]]
  return %slice : vector<2x!PF17>
}

//===----------------------------------------------------------------------===//
// CmpOp constant folding
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_cmp_fold
// CHECK-SAME: () -> i1 {
func.func @test_cmp_fold() -> i1 {
  // CHECK: %[[C:.*]] = arith.constant true
  %0 = field.constant 2 : !PF17
  %1 = field.constant 1 : !PF17
  %2 = field.cmp ugt, %0, %1 : !PF17
  // CHECK-NOT: field.cmp
  // CHECK: return %[[C]]
  return %2 : i1
}

// CHECK-LABEL: @test_cmp_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_cmp_tensor_fold() -> tensor<2xi1> {
  // CHECK: %[[C:.*]] = arith.constant dense<[true, false]> : [[T]]
  %0 = field.constant dense<[2, 2]> : tensor<2x!PF17>
  %1 = field.constant dense<[1, 3]> : tensor<2x!PF17>
  %2 = field.cmp ugt, %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.cmp
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2xi1>
}

// CHECK-LABEL: @test_cmp_splat_tensor_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_cmp_splat_tensor_fold() -> tensor<2xi1> {
  // CHECK: %[[C:.*]] = arith.constant dense<true> : [[T]]
  %0 = field.constant dense<2> : tensor<2x!PF17>
  %1 = field.constant dense<1> : tensor<2x!PF17>
  %2 = field.cmp ugt, %0, %1 : tensor<2x!PF17>
  // CHECK-NOT: field.cmp
  // CHECK: return %[[C]] : [[T]]
  return %2 : tensor<2xi1>
}

//===----------------------------------------------------------------------===//
// ToMont/FromMont cancellation
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_from_mont_to_mont_cancel
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_from_mont_to_mont_cancel(%arg0: !PF17) -> !PF17 {
  // CHECK-NOT: field.to_mont
  // CHECK-NOT: field.from_mont
  // CHECK: return %[[ARG0]] : [[T]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.from_mont %0 : !PF17
  return %1 : !PF17
}

// CHECK-LABEL: @test_from_mont_to_mont_tensor_cancel
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_from_mont_to_mont_tensor_cancel(%arg0: tensor<2x!PF17>) -> tensor<2x!PF17> {
  // CHECK-NOT: field.to_mont
  // CHECK-NOT: field.from_mont
  // CHECK: return %[[ARG0]] : [[T]]
  %0 = field.to_mont %arg0 : tensor<2x!PF17m>
  %1 = field.from_mont %0 : tensor<2x!PF17>
  return %1 : tensor<2x!PF17>
}

// CHECK-LABEL: @test_to_mont_from_mont_cancel
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_to_mont_from_mont_cancel(%arg0: !PF17m) -> !PF17m {
  // CHECK-NOT: field.from_mont
  // CHECK-NOT: field.to_mont
  // CHECK: return %[[ARG0]] : [[T]]
  %0 = field.from_mont %arg0 : !PF17
  %1 = field.to_mont %0 : !PF17m
  return %1 : !PF17m
}

// CHECK-LABEL: @test_to_mont_from_mont_tensor_cancel
// CHECK-SAME: (%[[ARG0:.*]]: [[T:.*]]) -> [[T]]
func.func @test_to_mont_from_mont_tensor_cancel(%arg0: tensor<2x!PF17m>) -> tensor<2x!PF17m> {
  // CHECK-NOT: field.from_mont
  // CHECK-NOT: field.to_mont
  // CHECK: return %[[ARG0]] : [[T]]
  %0 = field.from_mont %arg0 : tensor<2x!PF17>
  %1 = field.to_mont %0 : tensor<2x!PF17m>
  return %1 : tensor<2x!PF17m>
}

//===----------------------------------------------------------------------===//
// ToMont additive distributivity
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_add_of_to_mont
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[T]]) -> [[TM:.*]] {
func.func @test_add_of_to_mont(%arg0: !PF17, %arg1: !PF17) -> !PF17m {
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.to_mont %[[ADD]] : [[TM]]
  // CHECK: return %[[RES]] : [[TM]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.to_mont %arg1 : !PF17m
  %2 = field.add %0, %1 : !PF17m
  return %2 : !PF17m
}

// CHECK-LABEL: @test_sub_of_to_mont
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[T]]) -> [[TM:.*]] {
func.func @test_sub_of_to_mont(%arg0: !PF17, %arg1: !PF17) -> !PF17m {
  // CHECK: %[[SUB:.*]] = field.sub %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.to_mont %[[SUB]] : [[TM]]
  // CHECK: return %[[RES]] : [[TM]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.to_mont %arg1 : !PF17m
  %2 = field.sub %0, %1 : !PF17m
  return %2 : !PF17m
}

// CHECK-LABEL: @test_add_of_to_mont_tensor
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[T]]) -> [[TM:.*]] {
func.func @test_add_of_to_mont_tensor(%arg0: tensor<2x!PF17>, %arg1: tensor<2x!PF17>) -> tensor<2x!PF17m> {
  // CHECK: %[[ADD:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK: %[[RES:.*]] = field.to_mont %[[ADD]] : [[TM]]
  // CHECK: return %[[RES]] : [[TM]]
  %0 = field.to_mont %arg0 : tensor<2x!PF17m>
  %1 = field.to_mont %arg1 : tensor<2x!PF17m>
  %2 = field.add %0, %1 : tensor<2x!PF17m>
  return %2 : tensor<2x!PF17m>
}

// Both to_mont ops have an extra use; folding would net +1 op.
// CHECK-LABEL: @test_add_of_to_mont_multi_use_no_fold
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[T]])
func.func @test_add_of_to_mont_multi_use_no_fold(%arg0: !PF17, %arg1: !PF17)
    -> (!PF17m, !PF17m, !PF17m) {
  // CHECK: %[[TM0:.*]] = field.to_mont %[[ARG0]]
  // CHECK: %[[TM1:.*]] = field.to_mont %[[ARG1]]
  // CHECK: %[[ADD:.*]] = field.add %[[TM0]], %[[TM1]]
  // CHECK-NOT: field.to_mont
  // CHECK: return %[[ADD]], %[[TM0]], %[[TM1]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.to_mont %arg1 : !PF17m
  %2 = field.add %0, %1 : !PF17m
  return %2, %0, %1 : !PF17m, !PF17m, !PF17m
}

// Only one to_mont has an extra use; the other is dead after the fold.
// CHECK-LABEL: @test_add_of_to_mont_one_extra_use_folds
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[T]])
func.func @test_add_of_to_mont_one_extra_use_folds(%arg0: !PF17, %arg1: !PF17)
    -> (!PF17m, !PF17m) {
  // CHECK-DAG: %[[TM0:.*]] = field.to_mont %[[ARG0]] : [[TM:.*]]
  // CHECK-DAG: %[[ADD:.*]] = field.add %[[ARG0]], %[[ARG1]] : [[T]]
  // CHECK-DAG: %[[RES:.*]] = field.to_mont %[[ADD]] : [[TM]]
  // CHECK: return %[[RES]], %[[TM0]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.to_mont %arg1 : !PF17m
  %2 = field.add %0, %1 : !PF17m
  return %2, %0 : !PF17m, !PF17m
}

// Mixed: only one operand is to_mont. The pattern must NOT fire.
// CHECK-LABEL: @test_add_of_to_mont_mixed_no_fold
// CHECK-SAME: (%[[ARG0:.*]]: [[T:[^,]*]], %[[ARG1:.*]]: [[TM:[^)]*]]) -> [[TM]] {
func.func @test_add_of_to_mont_mixed_no_fold(%arg0: !PF17, %arg1: !PF17m) -> !PF17m {
  // CHECK: %[[TM0:.*]] = field.to_mont %[[ARG0]] : [[TM]]
  // CHECK: %[[RES:.*]] = field.add %[[TM0]], %[[ARG1]] : [[TM]]
  // CHECK: return %[[RES]] : [[TM]]
  %0 = field.to_mont %arg0 : !PF17m
  %1 = field.add %0, %arg1 : !PF17m
  return %1 : !PF17m
}

//===----------------------------------------------------------------------===//
// BitcastOp constant folding
//===----------------------------------------------------------------------===//

// Tensor: bitcast(arith.constant : tensor<2xi32>) -> tensor<2x!PF17> folds to
// a single field.constant of the same raw bits.
// CHECK-LABEL: @test_bitcast_from_int_to_pf_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_from_int_to_pf_fold() -> tensor<2x!PF17> {
  // CHECK: %[[C:.*]] = field.constant dense<[2, 3]> : [[T]]
  // CHECK-NOT: field.bitcast
  // CHECK: return %[[C]] : [[T]]
  %0 = arith.constant dense<[2, 3]> : tensor<2xi32>
  %1 = field.bitcast %0 : tensor<2xi32> -> tensor<2x!PF17>
  return %1 : tensor<2x!PF17>
}

// Reverse direction: bitcast(field.constant : tensor<2x!PF17>) -> tensor<2xi32>
// folds to an arith.constant with the same raw bits.
// CHECK-LABEL: @test_bitcast_from_pf_to_int_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_from_pf_to_int_fold() -> tensor<2xi32> {
  // CHECK: %[[C:.*]] = arith.constant dense<[2, 3]> : [[T]]
  // CHECK-NOT: field.bitcast
  // CHECK: return %[[C]] : [[T]]
  %0 = field.constant dense<[2, 3]> : tensor<2x!PF17>
  %1 = field.bitcast %0 : tensor<2x!PF17> -> tensor<2xi32>
  return %1 : tensor<2xi32>
}

// Scalar IntegerAttr operand: bitcast(arith.constant : i32) -> !PF17 folds to
// a scalar field.constant.
// CHECK-LABEL: @test_bitcast_scalar_int_to_pf_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_scalar_int_to_pf_fold() -> !PF17 {
  // CHECK: %[[C:.*]] = field.constant 5 : [[T]]
  // CHECK-NOT: field.bitcast
  // CHECK: return %[[C]] : [[T]]
  %0 = arith.constant 5 : i32
  %1 = field.bitcast %0 : i32 -> !PF17
  return %1 : !PF17
}

// Mont-encoded target: the materialized field.constant stores the input
// attribute's raw bits — no canonical->Mont conversion at fold time.
// CHECK-LABEL: @test_bitcast_int_to_pf_mont_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_int_to_pf_mont_fold() -> tensor<2x!PF17m> {
  // CHECK: %[[C:.*]] = field.constant dense<[2, 3]> : [[T]]
  // CHECK-NOT: field.bitcast
  // CHECK: return %[[C]] : [[T]]
  %0 = arith.constant dense<[2, 3]> : tensor<2xi32>
  %1 = field.bitcast %0 : tensor<2xi32> -> tensor<2x!PF17m>
  return %1 : tensor<2x!PF17m>
}

// Extension-field target: the constant fold MUST NOT fire because the
// field.constant attribute for tensor<Mx!EF<DxBase>> is shaped [M, D, ...]
// (tower dims appended), not the bitcast's flat [M*D*...]. A pass-through
// fold would produce an ill-formed constant. The bitcast must remain so
// field-to-llvm can lower it as a runtime memref reinterpret.
!EF2_17 = !field.ef<2x!PF17, 11:i32>
// CHECK-LABEL: @test_bitcast_int_to_ef_no_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_int_to_ef_no_fold() -> tensor<1x!EF2_17> {
  // CHECK: %[[C:.*]] = arith.constant dense<[2, 3]> : tensor<2xi32>
  // CHECK: %[[BC:.*]] = field.bitcast %[[C]] : tensor<2xi32> -> [[T]]
  // CHECK: return %[[BC]] : [[T]]
  %0 = arith.constant dense<[2, 3]> : tensor<2xi32>
  %1 = field.bitcast %0 : tensor<2xi32> -> tensor<1x!EF2_17>
  return %1 : tensor<1x!EF2_17>
}

// Element-wise EF where input and output shapes coincidentally agree:
// `tensor<1xi64>` and `tensor<1x!EF2_17>` both have shape [1] and 64 bits
// total. The template's shape gate matches, so the fold tries to materialize
// `field.constant dense<...> : tensor<1x!EF2_17>` with attribute shape [1]
// — but field.constant for EF requires attribute shape [1, 2] (tower dims
// appended). FieldDialect::materializeConstant detects the mismatch and
// returns nullptr, reverting the fold so the bitcast stays for field-to-llvm.
// CHECK-LABEL: @test_bitcast_element_wise_int_to_ef_no_fold
// CHECK-SAME: () -> [[T:.*]] {
func.func @test_bitcast_element_wise_int_to_ef_no_fold() -> tensor<1x!EF2_17> {
  // CHECK: %[[C:.*]] = arith.constant dense<42> : tensor<1xi64>
  // CHECK: %[[BC:.*]] = field.bitcast %[[C]] : tensor<1xi64> -> [[T]]
  // CHECK: return %[[BC]] : [[T]]
  %0 = arith.constant dense<42> : tensor<1xi64>
  %1 = field.bitcast %0 : tensor<1xi64> -> tensor<1x!EF2_17>
  return %1 : tensor<1x!EF2_17>
}
